# Generated by Django 4.2 on 2023-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='profession',
            new_name='profession1',
        ),
        migrations.AddField(
            model_name='contact',
            name='profession2',
            field=models.CharField(default='False', max_length=150),
        ),
    ]
