# Generated by Django 4.2 on 2023-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_profession_contact_profession1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profession1',
            field=models.CharField(default='False', max_length=150),
        ),
    ]
